---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    level: warning
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
  document-start:
    present: false
