apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama3-vector-db
  namespace: llama3-multi-adapter
  labels:
    app: qdrant
    component: vector-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
