apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-adapter-summarization
  namespace: llama3-multi-adapter
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: summarization-adapter
    app.kubernetes.io/component: adapter
    app.kubernetes.io/adapter-type: summarization
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: summarization-adapter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: summarization-adapter
        app.kubernetes.io/component: adapter
        app.kubernetes.io/adapter-type: summarization
        gpu-id: "1"
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: setup-permissions
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /adapters/.ollama/adapters
          chown -R 1001:1001 /adapters
          chmod -R 755 /adapters
        volumeMounts:
        - name: adapter-storage
          mountPath: /adapters
        securityContext:
          runAsUser: 0
      containers:
      - name: ollama
        image: ollama/ollama:0.3.11
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: HOME
          value: "/adapters"
        - name: OLLAMA_MODELS
          value: "/models/.ollama/models:/adapters/.ollama/adapters"
        - name: OLLAMA_ADAPTER_TYPE
          value: "summarization"
        - name: OLLAMA_KEEP_ALIVE
          value: "20m"
        - name: OLLAMA_MAX_LOADED_MODELS
          value: "1"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "1"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: CUDA_VISIBLE_DEVICES
          value: "1"
        - name: OLLAMA_GPU_DRIVER
          value: "cuda"
        - name: OLLAMA_NUM_PARALLEL
          value: "2"
        - name: OLLAMA_MAX_QUEUE
          value: "64"
        - name: OLLAMA_GPU_MEMORY_FRACTION
          value: "0.4"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop: [ALL]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: base-models
          mountPath: /models
          readOnly: true
        - name: adapter-storage
          mountPath: /adapters
        resources:
          requests:
            cpu: "2000m"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4000m"
            memory: "12Gi"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: base-models
        persistentVolumeClaim:
          claimName: llama3-base-models-pvc
      - name: adapter-storage
        persistentVolumeClaim:
          claimName: llama3-summarization-adapter-pvc
      nodeSelector:
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
