name: Feature Request
description: Suggest an improvement or new capability
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Tell us how we can make Diatonic AI's Kubernetes platform better.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see changed or added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change important?

  - type: textarea
    id: manifests
    attributes:
      label: Affected Manifests
      description: List related manifest paths if applicable.
      placeholder: |
        k8s-manifests/llama3-8b-deployment/multi-adapter/...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered done?
