---
# Production Let's Encrypt Issuer (requires valid domain and DNS)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/part-of: ssl-automation
spec:
  acme:
    # The ACME server URL (Let's Encrypt production)
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    # IMPORTANT: Replace with your actual email
    email: admin@yourdomain.com  # CHANGE THIS

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}

---
# Staging Let's Encrypt Issuer (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/part-of: ssl-automation
spec:
  acme:
    # The ACME server URL (Let's Encrypt staging)
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: admin@yourdomain.com  # CHANGE THIS

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}

---
# Self-Signed Issuer (for local testing without domain)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  labels:
    app.kubernetes.io/part-of: ssl-automation
spec:
  selfSigned: {}
