apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llama3-multi-adapter-ingress
  namespace: llama3-multi-adapter
  labels:
    app: llama3-multi-adapter
    component: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.example.com/oauth2/start?rd=$request_uri"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://console.example.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Content-Type"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-connections: "40"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload";
      more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self';";
      more_set_headers "Referrer-Policy: no-referrer";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - llama3.example.com
    secretName: llama3-multi-adapter-tls
  rules:
  - host: llama3.example.com
    http:
      paths:
      - path: /chatbot(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: llama3-chatbot-adapter
            port:
              number: 8080
      - path: /code(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: llama3-code-adapter
            port:
              number: 8080
      - path: /rag(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: llama3-rag-adapter
            port:
              number: 8080
      - path: /architecture(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: llama3-microservices-adapter
            port:
              number: 8080
      - path: /base(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: llama3-base-model
            port:
              number: 8080
      - path: /health
        pathType: Exact
        backend:
          service:
            name: llama3-base-model
            port:
              number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: llama3-multi-adapter
data:
  custom-headers.conf: |
    add_header X-Powered-By "" always;
  rate-limit.conf: |
    limit_req_zone $binary_remote_addr zone=general:10m rate=20r/s;
    limit_conn_zone $binary_remote_addr zone=connections:10m;
