apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  namespace: llama3-multi-adapter
  labels:
    app: qdrant
    component: vector-db
data:
  config.yaml: |
    log_level: INFO
    
    service:
      host: 0.0.0.0
      http_port: 6333
      grpc_port: 6334
      enable_tls: false
    
    storage:
      # Storage directory inside container
      storage_path: /qdrant/storage
      
      # Snapshots configuration
      snapshots_path: /qdrant/snapshots
      
      # Optimize for performance
      optimizers:
        deleted_threshold: 0.2
        vacuum_min_vector_number: 1000
        default_segment_number: 0
        max_segment_size_kb: 200000
        memmap_threshold_kb: 50000
        indexing_threshold_kb: 20000
        flush_interval_sec: 5
        max_optimization_threads: 1
    
    # Performance tuning
    cluster:
      enabled: false
    
    # Collection defaults
    collection:
      # Use HNSW for high-performance approximate nearest neighbor search
      hnsw_config:
        m: 16
        ef_construct: 100
        full_scan_threshold: 10000
      
      # Optimize for vectors typical of embeddings (768-1024 dimensions)
      optimizer_config:
        deleted_threshold: 0.2
        vacuum_min_vector_number: 1000
        default_segment_number: 0
        max_segment_size: 200000
        memmap_threshold: 50000
        indexing_threshold: 20000
        flush_interval_sec: 5
        max_optimization_threads: 1
      
      # WAL configuration for durability
      wal_config:
        wal_capacity_mb: 32
        wal_segments_ahead: 0
    
    # Resource limits
    runtime:
      max_request_size_mb: 32
      max_workers: 0  # Auto-detect based on CPUs
