apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: llama3-multi-adapter
  labels:
    app: qdrant
    component: vector-db
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: 6333
    protocol: TCP
  - name: grpc
    port: 6334
    targetPort: 6334
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-api
  namespace: llama3-multi-adapter
  labels:
    app: qdrant
    component: vector-db
spec:
  type: ClusterIP
  selector:
    app: qdrant
  ports:
  - name: http
    port: 6333
    targetPort: 6333
    protocol: TCP
  - name: grpc
    port: 6334
    targetPort: 6334
    protocol: TCP
