apiVersion: v1
kind: Service
metadata:
  name: ollama-base
  namespace: llama3-multi-adapter
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: base
    app.kubernetes.io/component: base-model
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: base
