apiVersion: v1
kind: Service
metadata:
  name: ollama-chatbot
  namespace: llama3-multi-adapter
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: chatbot-adapter
    app.kubernetes.io/component: adapter
    app.kubernetes.io/adapter-type: chatbot
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: chatbot-adapter
  sessionAffinity: ClientIP  # Sticky sessions for better caching
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour
