name: CI

on:
  push:
    branches: [ main, feature/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML
        run: yamllint -c .yamllint.yaml .

      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | tar -xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate manifests
        run: |
          find k8s-manifests -name "*.yaml" -o -name "*.yml" | xargs kubeconform -summary -verbose
